from typing import Annotated, Dict, Any, List, Optional
from typing_extensions import NotRequired, TypedDict
from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages


def merge_variables(left: dict, right: dict) -> dict:
    """Reducer: shallow-merge node variable updates, with right-hand values winning."""
    if not left:
        left = {}
    if not right:
        right = {}
    return {**left, **right}


class FlowState(TypedDict):
    """Typed state shared by dynamically compiled LangGraph workflows.

    Optional fields are declared as ``NotRequired`` because initial invocations,
    child flows, and node-isolation tests intentionally provide different
    subsets.  This matches the existing runtime behavior while documenting the
    thread/auth fields needed by the v2 agent harness.
    """

    # System context
    session_id: str
    user_id: str
    thread_id: NotRequired[str]
    tenant_id: NotRequired[str]
    auth_context: NotRequired[Dict[str, Any]]

    # Dynamic variables generated by tools (for example {{customer_id}})
    variables: Annotated[Dict[str, Any], merge_variables]

    # Conversational memory for LLMs
    messages: Annotated[List[AnyMessage], add_messages]

    # Iterator/map-reduce state
    current_iteration_item: NotRequired[Optional[Any]]

    # Error tracking
    error: NotRequired[Optional[str]]
