from typing import Annotated, Dict, Any, List, Optional
from typing_extensions import TypedDict
from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages

def merge_variables(left: dict, right: dict) -> dict:
    """Reducer: Deep merges flow variables generated by nodes."""
    if not left:
        left = {}
    if not right:
        right = {}
    # Merge right into left, overwriting existing keys
    return {**left, **right}

class FlowState(TypedDict):
    """The strictly typed state for the LangGraph workflow."""
    
    # System Context
    session_id: str
    user_id: str
    
    # Dynamic variables generated by tools (e.g., {{customer_id}})
    variables: Annotated[Dict[str, Any], merge_variables]
    
    # Conversational memory for LLMs
    messages: Annotated[List[AnyMessage], add_messages]
    
    # For Iterator/Map-Reduce loops (Current item being processed)
    current_iteration_item: Optional[Any]
    
    # Error tracking
    error: Optional[str]